# Var name can contain letters, numbers and underscore
# Applied variable name must be between {{ and }}, whitespace chars are ignored before/after name
vars:
  euCities: "Ostrava|Prague"
  entityAlias: "journey"
  date_part1: "(day|week|first Monday in the month)"

# If not absolute path to file, then is relative to this YAML file
# If file path is not string, file is not created
output:
  dialogFlowJSONFile: "dialogFlowOutput.json"
  stdout: true

random:
  seed: null # Set any string to static seed to the random generator - keep null to be reasonably unpredictable
  contextualSeed: true

# Global entities settings
entities:
  "@journeyEU":
    alias: "{{ entityAlias }}"
    meta: "@{{ entityAlias }}"
    phrases:
      - "({{euCities}}) to (Paris|Berlin)"
      - "(Bratislava|Vienna) to (Madrid|Helsinki)"

  "@journeyWorld":
    # Alias and meta is derived from entity name
    phrases:
      - "(Amsterdam|Oslo) to (New York|Washington)"

sentences:
# This sentence will result in 4 sentences
- "I( am|'m) Pavel( from Ostrava)?"

# Taking journeyEU from global scope
# Sentence will result in 6 sentences and will be repeated twice. Totally will be printed 12 times
- sentence: "Flying from @journeyEU every {{ date_part1 }} in the (morning|evening)"
  repeat: 2

# This override global scope of journeyEU
- entities:
    "@journeyEU":
      alias: "{{ entityAlias }}"
      meta: "@{{ entityAlias }}"
      phrases:
        - "(Krakow|Wroclaw) to (Venice|Munich)"

# @journeyEU phrases are overridden only for this once sentence
- "Domestic flights from @journeyEU{(Ostrava|Brno) to Pardubice;Pardubice to (Ostrava|Brno)} (once|twice|three times) per (week|month)"

# @journeyEU here uses again global scope
# ? is escaped here to not be taken into regular expression
- "Are you flying from (@journeyEU|@journeyWorld) every {{ date_part1 }}\\?"
